# Generated by Django 5.2.8 on 2025-11-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(db_column='ID_PRODUTO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME_PRODUTO', max_length=120)),
                ('descricao', models.TextField(db_column='DESCRICAO')),
                ('preco', models.DecimalField(db_column='PRECO', decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.IntegerField(db_column='QUANTIDADE_ESTOQUE')),
                ('estoque_minimo', models.IntegerField(db_column='ESTOQUE_MINIMO')),
            ],
            options={
                'db_table': 'PRODUTO',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
                ('email', models.EmailField(db_column='EMAIL', max_length=254, unique=True)),
                ('senha', models.CharField(db_column='SENHA', max_length=255)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.AutoField(db_column='ID_MOVIMENTACAO', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], db_column='TIPO_MOVIMENTACAO', max_length=10)),
                ('quantidade', models.IntegerField(db_column='QUANTIDADE')),
                ('data', models.DateField(db_column='DATA_MOVIMENTACAO')),
                ('produto', models.ForeignKey(db_column='ID_PRODUTO', on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
                ('usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'MOVIMENTACAO_ESTOQUE',
            },
        ),
    ]
